import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        GameLibrary gameLibrary = new GameLibrary();
        Scanner scanner = new Scanner(System.in);
        // Экшн игры
        gameLibrary.addGame("Action", "Metal Gear 2: Solid Snake", "Single");
        gameLibrary.addGame("Action", "Batman 1989", "Single");
        gameLibrary.addGame("Action", "Chip ’n Dale Rescue Rangers: The Adventures in Nimnul’s Castle", "Single");
        gameLibrary.addGame("Action", "Predator 2", "Single");
        gameLibrary.addGame("Action", "Mad Max", "Single");
        gameLibrary.addGame("Action", "Terminator 2: Judgment Day", "Single");
        gameLibrary.addGame("Action", "Golden Axe II", "Single");
        gameLibrary.addGame("Action", "Golden Axe II", "Multi");
        gameLibrary.addGame("Action", "Worms", "Single");
        gameLibrary.addGame("Action", "Worms", "Multi");
        gameLibrary.addGame("Action", "Grand Theft Auto", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto", "Multi");
        gameLibrary.addGame("Action", "Metal Gear Solid", "Single");
        gameLibrary.addGame("Action", "Thief: The Dark Project", "Single");
        gameLibrary.addGame("Action", "Hitman: Codename 47", "Single");
        gameLibrary.addGame("Action", "Crash Bash", "Single");
        gameLibrary.addGame("Action", "Crash Bash", "Multi");
        gameLibrary.addGame("Action", "Oni", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto III", "Single");
        gameLibrary.addGame("Action", "Devil May Cry", "Single");
        gameLibrary.addGame("Action", "Hitman 2: Silent Assassin", "Single");
        gameLibrary.addGame("Action", "BloodRayne", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto: Vice City", "Single");
        gameLibrary.addGame("Action", "The Simpsons Hit & Run", "Single");
        gameLibrary.addGame("Action", "Max Payne 2: The Fall of Max Payne", "Single");
        gameLibrary.addGame("Action", "Hitman: Contracts", "Single");
        gameLibrary.addGame("Action", "Metal Gear Solid 3: Snake Eater", "Single");
        gameLibrary.addGame("Action", "Metal Gear Solid 3: Snake Eater", "Multi");
        gameLibrary.addGame("Action", "Grand Theft Auto: San Andreas", "Single");
        gameLibrary.addGame("Action", "Hitman: Contracts", "Single");
        gameLibrary.addGame("Action", "Metal Gear Solid 3: Snake Eater", "Single");
        gameLibrary.addGame("Action", "Metal Gear Solid 3: Snake Eater", "Multi");
        gameLibrary.addGame("Action", "Grand Theft Auto: San Andreas", "Single");
        gameLibrary.addGame("Action", "The Godfather: The Game", "Single");
        gameLibrary.addGame("Action", "Hitman: Blood Money", "Single");
        gameLibrary.addGame("Action", "Titan Quest", "Single");
        gameLibrary.addGame("Action", "Titan Quest", "Multi");
        gameLibrary.addGame("Action", "Dead Rising", "Single");
        gameLibrary.addGame("Action", "Saints Row", "Single");
        gameLibrary.addGame("Action", "S.T.A.L.K.E.R.: Тень Чернобыля", "Single");
        gameLibrary.addGame("Action", "S.T.A.L.K.E.R.: Тень Чернобыля", "Multi");
        gameLibrary.addGame("Action", "TMNT", "Single");
        gameLibrary.addGame("Action", "Sam & Max Save the World", "Single");
        gameLibrary.addGame("Action", "Portal", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto IV", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto IV", "Multi");
        gameLibrary.addGame("Action", "Assassin’s Creed", "Single");
        gameLibrary.addGame("Action", "Saints Row 2", "Single");
        gameLibrary.addGame("Action", "Saints Row 2", "Multi");
        gameLibrary.addGame("Action", "Mount & Blade", "Single");
        gameLibrary.addGame("Action", "Mount & Blade", "Multi");
        gameLibrary.addGame("Action", "Prototype", "Single");
        gameLibrary.addGame("Action", "Batman: Arkham Asylum", "Single");
        gameLibrary.addGame("Action", "Resident Evil 5", "Single");
        gameLibrary.addGame("Action", "Resident Evil 5", "Multi");
        gameLibrary.addGame("Action", "Borderlands", "Single");
        gameLibrary.addGame("Action", "Borderlands", "Multi");
        gameLibrary.addGame("Action", "BioShock 2", "Single");
        gameLibrary.addGame("Action", "BioShock 2", "Multi");
        gameLibrary.addGame("Action", "Heavy Rain", "Single");
        gameLibrary.addGame("Action", "Just Cause 2", "Single");
        gameLibrary.addGame("Action", "Mafia II", "Single");
        gameLibrary.addGame("Action", "Kane & Lynch 2: Dog Days", "Single");
        gameLibrary.addGame("Action", "Kane & Lynch 2: Dog Days", "Multi");
        gameLibrary.addGame("Action", "Ведьмак 2: Убийцы королей", "Single");
        gameLibrary.addGame("Action", "Batman: Arkham City", "Single");
        gameLibrary.addGame("Action", "Deus Ex: Human Revolution", "Single");
        gameLibrary.addGame("Action", "L.A. Noire", "Single");
        gameLibrary.addGame("Action", "Magicka", "Single");
        gameLibrary.addGame("Action", "Magicka", "Multi");
        gameLibrary.addGame("Action", "Minecraft", "Single");
        gameLibrary.addGame("Action", "Minecraft", "Multi");
        gameLibrary.addGame("Action", "Borderlands 2", "Single");
        gameLibrary.addGame("Action", "Borderlands 2", "Multi");
        gameLibrary.addGame("Action", "Chivalry: Medieval Warfare", "Single");
        gameLibrary.addGame("Action", "Chivalry: Medieval Warfare", "Multi");
        gameLibrary.addGame("Action", "Dishonored", "Single");
        gameLibrary.addGame("Action", "Hotline Miami", "Single");
        gameLibrary.addGame("Action", "Max Payne 3", "Single");
        gameLibrary.addGame("Action", "Max Payne 3", "Multi");
        gameLibrary.addGame("Action", "Prototype 2", "Single");
        gameLibrary.addGame("Action", "Assassin’s Creed IV: Black Flag", "Single");
        gameLibrary.addGame("Action", "Assassin’s Creed IV: Black Flag", "Multi");
        gameLibrary.addGame("Action", "Batman: Arkham Origins", "Single");
        gameLibrary.addGame("Action", "Batman: Arkham Origins", "Multi");
        gameLibrary.addGame("Action", "BioShock Infinite", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto V", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto V", "Multi");
        gameLibrary.addGame("Action", "The Last of Us", "Single");
        gameLibrary.addGame("Action", "The Last of Us", "Multi");
        gameLibrary.addGame("Action", "Project Zomboid", "Single");
        gameLibrary.addGame("Action", "Project Zomboid", "Multi");
        gameLibrary.addGame("Action", "Saints Row IV", "Single");
        gameLibrary.addGame("Action", "Saints Row IV", "Multi");
        gameLibrary.addGame("Action", "Middle-earth: Shadow of Mordor", "Single");
        gameLibrary.addGame("Action", "The Long Dark", "Single");
        gameLibrary.addGame("Action", "Styx: Master of Shadows", "Single");
        gameLibrary.addGame("Action", "The Witcher 3: Wild Hunt", "Single");
        gameLibrary.addGame("Action", "Batman: Arkham Knight", "Single");
        gameLibrary.addGame("Action", "Dying Light", "Single");
        gameLibrary.addGame("Action", "Dying Light", "Multi");
        gameLibrary.addGame("Action", "Fallout 4", "Single");
        gameLibrary.addGame("Action", "I Am Bread", "Single");
        gameLibrary.addGame("Action", "I Am Bread", "Multi");
        gameLibrary.addGame("Action", "Life Is Strange", "Single");
        gameLibrary.addGame("Action", "Mad Max", "Single");
        gameLibrary.addGame("Action", "Hitman (2016)", "Single");
        gameLibrary.addGame("Action", "Tom Clancy’s The Division", "Single");
        gameLibrary.addGame("Action", "Tom Clancy’s The Division", "Multi");
        gameLibrary.addGame("Action", "Assassin’s Creed Origins", "Single");
        gameLibrary.addGame("Action", "Life Is Strange: Before the Storm", "Single");
        gameLibrary.addGame("Action", "Middle-earth: Shadow of War", "Single");
        gameLibrary.addGame("Action", "Middle-earth: Shadow of War", "Multi");
        gameLibrary.addGame("Action", "Nier: Automata", "Single");
        gameLibrary.addGame("Action", "Prey (2017)", "Single");
        gameLibrary.addGame("Action", "Assassin’s Creed Origins", "Single");
        gameLibrary.addGame("Action", "Life Is Strange: Before the Storm", "Single");
        gameLibrary.addGame("Action", "Middle-earth: Shadow of War", "Single");
        gameLibrary.addGame("Action", "Middle-earth: Shadow of War", "Multi");
        gameLibrary.addGame("Action", "Nier: Automata", "Single");
        gameLibrary.addGame("Action", "Prey (2017)", "Single");
        gameLibrary.addGame("Action", "A Way Out", "Single");
        gameLibrary.addGame("Action", "A Way Out", "Multi");
        gameLibrary.addGame("Action", "Detroit: Become Human", "Single");
        gameLibrary.addGame("Action", "Far Cry 5", "Single");
        gameLibrary.addGame("Action", "Far Cry 5", "Multi");
        gameLibrary.addGame("Action", "Kingdom Come: Deliverance", "Single");
        gameLibrary.addGame("Action", "Red Dead Redemption 2", "Single");
        gameLibrary.addGame("Action", "Red Dead Redemption 2", "Multi");
        gameLibrary.addGame("Action", "Monster Hunter: World", "Single");
        gameLibrary.addGame("Action", "Monster Hunter: World", "Multi");
        gameLibrary.addGame("Action", "Spider-Man (2018)", "Single");
        gameLibrary.addGame("Action", "Death Stranding", "Single");
        gameLibrary.addGame("Action", "Devil May Cry 5", "Single");
        gameLibrary.addGame("Action", "Mordhau", "Single");
        gameLibrary.addGame("Action", "Mordhau", "Multi");
        gameLibrary.addGame("Action", "Untitled Goose Game", "Single");
        gameLibrary.addGame("Action", "Star Wars Jedi: Fallen Order", "Single");
        gameLibrary.addGame("Action", "Shenmue III", "Single");
        gameLibrary.addGame("Action", "Cyberpunk 2077", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto", "Single");
        gameLibrary.addGame("Action", "Grand Theft Auto", "Multi");
        gameLibrary.addGame("Action", "The Punisher", "Single");
        gameLibrary.addGame("Action", "Devil May Cry 3: Dante’s Awakening", "Single");

        // Ролевые игры
        gameLibrary.addGame("RPG", "Final Fantasy III", "Single");
        gameLibrary.addGame("RPG", "Final Fantasy IV", "Single");
        gameLibrary.addGame("RPG", "Ultima Underworld: The Stygian Abyss", "Single");
        gameLibrary.addGame("RPG", "The Elder Scrolls: Arena", "Single");
        gameLibrary.addGame("RPG", "Diablo", "Single");
        gameLibrary.addGame("RPG", "Diablo", "Multi");
        gameLibrary.addGame("RPG", "Castlevania: Symphony of the Night", "Single");
        gameLibrary.addGame("RPG", "Fallout", "Single");
        gameLibrary.addGame("RPG", "Fallout 2", "Single");
        gameLibrary.addGame("RPG", "Baldur’s Gate 2", "Single");
        gameLibrary.addGame("RPG", "Baldur’s Gate 2", "Multi");
        gameLibrary.addGame("RPG", "Diablo II", "Single");
        gameLibrary.addGame("RPG", "Diablo II", "Multi");
        gameLibrary.addGame("RPG", "Nox", "Single");
        gameLibrary.addGame("RPG", "Nox", "Multi");
        gameLibrary.addGame("RPG", "The Elder Scrolls III: Morrowind", "Single");
        gameLibrary.addGame("RPG", "Neverwinter Nights", "Single");
        gameLibrary.addGame("RPG", "Neverwinter Nights", "Multi");
        gameLibrary.addGame("RPG", "Arx Fatalis", "Single");
        gameLibrary.addGame("RPG", "Star Wars: Knights of the Old Republic", "Single");
        gameLibrary.addGame("RPG", "The Elder Scrolls IV: Oblivion", "Single");
        gameLibrary.addGame("RPG", "Fallout 3", "Single");
        gameLibrary.addGame("RPG", "Mass Effect 2", "Single");
        gameLibrary.addGame("RPG", "The Elder Scrolls V: Skyrim", "Single");
        gameLibrary.addGame("RPG", "Dragon’s Dogma", "Single");
        gameLibrary.addGame("RPG", "Divinity: Original Sin", "Single");
        gameLibrary.addGame("RPG", "Divinity: Original Sin", "Multi");
        gameLibrary.addGame("RPG", "ATOM RPG", "Single");
        gameLibrary.addGame("RPG", "Kenshi", "Single");
        gameLibrary.addGame("RPG", "Disco Elysium", "Single");
        gameLibrary.addGame("RPG", "Yakuza: Like a Dragon", "Single");
        gameLibrary.addGame("RPG", "Star Wars: Knights of the Old Republic II – The Sith Lords", "Single");
        gameLibrary.addGame("RPG", "Fable", "Single");
        // Shooter
        gameLibrary.addGame("Shooter", "Doom", "Single");
        gameLibrary.addGame("Shooter", "Doom", "Multi");
        gameLibrary.addGame("Shooter", "Heretic", "Single");
        gameLibrary.addGame("Shooter", "Heretic", "Multi");
        gameLibrary.addGame("Shooter", "Doom II: Hell on Earth", "Single");
        gameLibrary.addGame("Shooter", "Doom II: Hell on Earth", "Multi");
        gameLibrary.addGame("Shooter", "Hexen", "Single");
        gameLibrary.addGame("Shooter", "Hexen", "Multi");
        gameLibrary.addGame("Shooter", "Star Wars: Dark Forces", "Single");
        gameLibrary.addGame("Shooter", "Quake", "Single");
        gameLibrary.addGame("Shooter", "Quake", "Multi");
        gameLibrary.addGame("Shooter", "Duke Nukem 3D", "Single");
        gameLibrary.addGame("Shooter", "Duke Nukem 3D", "Multi");
        gameLibrary.addGame("Shooter", "Final Doom", "Single");
        gameLibrary.addGame("Shooter", "Final Doom", "Multi");
        gameLibrary.addGame("Shooter", "Blood", "Single");
        gameLibrary.addGame("Shooter", "Blood", "Multi");
        gameLibrary.addGame("Shooter", "Doom 64", "Single");
        gameLibrary.addGame("Shooter", "GoldenEye 007", "Single");
        gameLibrary.addGame("Shooter", "GoldenEye 007", "Multi");
        gameLibrary.addGame("Shooter", "Quake II", "Single");
        gameLibrary.addGame("Shooter", "Quake II", "Multi");
        gameLibrary.addGame("Shooter", "Half-Life", "Single");
        gameLibrary.addGame("Shooter", "Half-Life", "Multi");
        gameLibrary.addGame("Shooter", "Tom Clancy’s Rainbow Six", "Single");
        gameLibrary.addGame("Shooter", "Tom Clancy’s Rainbow Six", "Multi");
        gameLibrary.addGame("Shooter", "Counter-Strike", "Single");
        gameLibrary.addGame("Shooter", "Counter-Strike", "Multi");
        gameLibrary.addGame("Shooter", "Kingpin: Life of Crime", "Single");
        gameLibrary.addGame("Shooter", "Kingpin: Life of Crime", "Multi");
        gameLibrary.addGame("Shooter", "Medal of Honor", "Single");
        gameLibrary.addGame("Shooter", "Medal of Honor", "Multi");
        gameLibrary.addGame("Shooter", "Quake III", "Single");
        gameLibrary.addGame("Shooter", "Quake III", "Multi");
        gameLibrary.addGame("Shooter", "Deus Ex", "Single");
        gameLibrary.addGame("Shooter", "Deus Ex", "Multi");
        gameLibrary.addGame("Shooter", "Medal of Honor: Underground", "Single");
        gameLibrary.addGame("Shooter", "Medal of Honor: Underground", "Multi");
        gameLibrary.addGame("Shooter", "Quake III: Team Arena", "Single");
        gameLibrary.addGame("Shooter", "Quake III: Team Arena", "Multi");
        gameLibrary.addGame("Shooter", "Half-Life: Blue Shift", "Single");
        gameLibrary.addGame("Shooter", "Half-Life: Blue Shift", "Multi");
        gameLibrary.addGame("Shooter", "Operation Flashpoint: Cold War Crisis", "Single");
        gameLibrary.addGame("Shooter", "Operation Flashpoint: Cold War Crisis", "Multi");
        gameLibrary.addGame("Shooter", "Red Faction", "Single");
        gameLibrary.addGame("Shooter", "Red Faction", "Multi");
        gameLibrary.addGame("Shooter", "Halo: Combat Evolved", "Single");
        gameLibrary.addGame("Shooter", "Halo: Combat Evolved", "Multi");
        gameLibrary.addGame("Shooter", "Max Payne", "Single");
        gameLibrary.addGame("Action", "Devil May Cry", "Single");
        gameLibrary.addGame("Shooter", "Medal of Honor: Allied Assault", "Single");
        gameLibrary.addGame("Shooter", "Medal of Honor: Allied Assault", "Multi");
        gameLibrary.addGame("Shooter", "Battlefield 1942", "Single");
        gameLibrary.addGame("Shooter", "Battlefield 1942", "Multi");
        gameLibrary.addGame("Shooter", "Postal 2", "Single");
        gameLibrary.addGame("Shooter", "Postal 2", "Multi");
        gameLibrary.addGame("Shooter", "Call of Duty", "Single");
        gameLibrary.addGame("Shooter", "Call of Duty", "Multi");
        gameLibrary.addGame("Shooter", "Hidden & Dangerous 2", "Single");
        gameLibrary.addGame("Shooter", "Hidden & Dangerous 2", "Multi");
        gameLibrary.addGame("Shooter", "Far Cry", "Single");
        gameLibrary.addGame("Shooter", "Far Cry", "Multi");
        gameLibrary.addGame("Shooter", "Doom 3", "Single");
        gameLibrary.addGame("Shooter", "Doom 3", "Multi");
        gameLibrary.addGame("Shooter", "Half Life 2", "Single");
        gameLibrary.addGame("Shooter", "Half Life 2", "Multi");
        gameLibrary.addGame("Shooter", "Halo 2", "Single");
        gameLibrary.addGame("Shooter", "Halo 2", "Multi");
        gameLibrary.addGame("Shooter", "Far Cry", "Single");
        gameLibrary.addGame("Shooter", "Far Cry", "Multi");
        gameLibrary.addGame("Shooter", "Doom 3", "Single");
        gameLibrary.addGame("Shooter", "Doom 3", "Multi");
        gameLibrary.addGame("Shooter", "Half Life 2", "Single");
        gameLibrary.addGame("Shooter", "Half Life 2", "Multi");
        gameLibrary.addGame("Shooter", "Halo 2", "Single");
        gameLibrary.addGame("Shooter", "Halo 2", "Multi");
        gameLibrary.addGame("Shooter", "Serious Sam II", "Single");
        gameLibrary.addGame("Shooter", "Serious Sam II", "Multi");
        gameLibrary.addGame("Shooter", "Quake 4", "Single");
        gameLibrary.addGame("Shooter", "Quake 4", "Multi");
        gameLibrary.addGame("Shooter", "Call of Duty 2", "Single");
        gameLibrary.addGame("Shooter", "Call of Duty 2", "Multi");
        gameLibrary.addGame("Shooter", "Battlefield 2", "Single");
        gameLibrary.addGame("Shooter", "Battlefield 2", "Multi");
        gameLibrary.addGame("Shooter", "Prey", "Single");
        gameLibrary.addGame("Shooter", "Prey", "Multi");
        gameLibrary.addGame("Shooter", "Medal of Honor: Airborne", "Single");
        gameLibrary.addGame("Shooter", "Medal of Honor: Airborne", "Multi");
        gameLibrary.addGame("Shooter", "Crysis", "Single");
        gameLibrary.addGame("Shooter", "Crysis", "Multi");
        gameLibrary.addGame("Shooter", "Halo 3", "Single");
        gameLibrary.addGame("Shooter", "Halo 3", "Multi");
        gameLibrary.addGame("Shooter", "Turok", "Single");
        gameLibrary.addGame("Shooter", "Turok", "Multi");
        gameLibrary.addGame("Shooter", "Battlefield: Bad Company", "Single");
        gameLibrary.addGame("Shooter", "Battlefield: Bad Company", "Multi");
        gameLibrary.addGame("Shooter", "S.T.A.L.K.E.R.: Чистое небо", "Single");
        gameLibrary.addGame("Shooter", "S.T.A.L.K.E.R.: Чистое небо", "Multi");
        gameLibrary.addGame("Shooter", "Crysis Warhead", "Single");
        gameLibrary.addGame("Shooter", "Crysis Warhead", "Multi");
        gameLibrary.addGame("Shooter", "Wolfenstein", "Single");
        gameLibrary.addGame("Shooter", "Wolfenstein", "Multi");
        gameLibrary.addGame("Shooter", "Halo 3: ODST", "Single");
        gameLibrary.addGame("Shooter", "Halo 3: ODST", "Multi");
        gameLibrary.addGame("Shooter", "S.T.A.L.K.E.R.: Зов Припяти", "Single");
        gameLibrary.addGame("Shooter", "S.T.A.L.K.E.R.: Зов Припяти", "Multi");
        gameLibrary.addGame("Shooter", "Call of Duty: Modern Warfare 2", "Single");
        gameLibrary.addGame("Shooter", "Call of Duty: Modern Warfare 2", "Multi");
        gameLibrary.addGame("Shooter", "Sniper: Ghost Warrior", "Single");
        gameLibrary.addGame("Shooter", "Sniper: Ghost Warrior", "Multi");
        gameLibrary.addGame("Shooter", "Battlefield 3", "Single");
        gameLibrary.addGame("Shooter", "Battlefield 3", "Multi");
        gameLibrary.addGame("Shooter", "Duke Nukem Forever", "Single");
        gameLibrary.addGame("Shooter", "Duke Nukem Forever", "Multi");
        gameLibrary.addGame("Shooter", "Homefront", "Single");
        gameLibrary.addGame("Shooter", "Homefront", "Multi");
        gameLibrary.addGame("Shooter", "Arma 3", "Single");
        gameLibrary.addGame("Shooter", "Arma 3", "Multi");
        gameLibrary.addGame("Shooter", "Payday 2", "Single");
        gameLibrary.addGame("Shooter", "Payday 2", "Multi");
        gameLibrary.addGame("Shooter", "Far Cry 4", "Single");
        gameLibrary.addGame("Shooter", "Far Cry 4", "Multi");
        gameLibrary.addGame("Shooter", "Insurgency", "Single");
        gameLibrary.addGame("Shooter", "Insurgency", "Multi");
        gameLibrary.addGame("Shooter", "Doom (2016)", "Single");
        gameLibrary.addGame("Shooter", "Doom (2016)", "Multi");
        gameLibrary.addGame("Shooter", "Superhot", "Single");
        gameLibrary.addGame("Shooter", "Homefront: The Revolution", "Single");
        gameLibrary.addGame("Shooter", "Homefront: The Revolution", "Multi");
        gameLibrary.addGame("Shooter", "Overwatch", "Single");
        gameLibrary.addGame("Shooter", "Overwatch", "Multi");
        gameLibrary.addGame("Shooter", "Day of Infamy", "Single");
        gameLibrary.addGame("Shooter", "Day of Infamy", "Multi");
        gameLibrary.addGame("Shooter", "Mass Effect: Andromeda", "Single");
        gameLibrary.addGame("Shooter", "Mass Effect: Andromeda", "Multi");
        gameLibrary.addGame("Shooter", "Terminator: Resistance", "Single");
        gameLibrary.addGame("Shooter", "Black Mesa", "Single");
        gameLibrary.addGame("Shooter", "Black Mesa", "Multi");
        gameLibrary.addGame("Shooter", "Deep Rock Galactic", "Single");
        gameLibrary.addGame("Shooter", "Deep Rock Galactic", "Multi");
        gameLibrary.addGame("Shooter", "Doom Eternal", "Single");
        gameLibrary.addGame("Shooter", "Doom Eternal", "Multi");
        gameLibrary.addGame("Shooter", "Half-Life: Alyx", "Single");
        gameLibrary.addGame("Shooter", "Predator: Hunting Grounds", "Multi");

        // Стратегии
        gameLibrary.addGame("Strategy", "Space Crusade", "Multi");
        gameLibrary.addGame("Strategy", "Dune II", "Single");
        gameLibrary.addGame("Strategy", "Syndicate", "Multi");
        gameLibrary.addGame("Strategy", "Syndicate", "Single");
        gameLibrary.addGame("Strategy", "Sid Meier’s Colonization", "Single");
        gameLibrary.addGame("Strategy", "Jagged Alliance", "Single");
        gameLibrary.addGame("Strategy", "Warcraft II: Tides of Darkness", "Single");
        gameLibrary.addGame("Strategy", "Warcraft II: Tides of Darkness", "Multi");
        gameLibrary.addGame("Strategy", "StarCraft", "Single");
        gameLibrary.addGame("Strategy", "StarCraft", "Multi");
        gameLibrary.addGame("Strategy", "Warcraft III: Reign of Chaos", "Single");
        gameLibrary.addGame("Strategy", "Warcraft III: Reign of Chaos", "Multi");
        gameLibrary.addGame("Strategy", "SimCity 4", "Single");
        gameLibrary.addGame("Strategy", "В тылу врага", "Single");
        gameLibrary.addGame("Strategy", "В тылу врага", "Multi");
        gameLibrary.addGame("Strategy", "Warhammer 40,000: Dawn of War", "Single");
        gameLibrary.addGame("Strategy", "Warhammer 40,000: Dawn of War", "Multi");
        gameLibrary.addGame("Strategy", "В тылу врага", "Single");
        gameLibrary.addGame("Strategy", "В тылу врага", "Multi");
        gameLibrary.addGame("Strategy", "Warhammer 40,000: Dawn of War", "Single");
        gameLibrary.addGame("Strategy", "Warhammer 40,000: Dawn of War", "Multi");
        gameLibrary.addGame("Strategy", "Star Wars: Empire at War", "Single");
        gameLibrary.addGame("Strategy", "Star Wars: Empire at War", "Multi");
        gameLibrary.addGame("Strategy", "The Lord of the Rings: The Battle for Middle-earth II", "Single");
        gameLibrary.addGame("Strategy", "The Lord of the Rings: The Battle for Middle-earth II", "Multi");
        gameLibrary.addGame("Strategy", "7.62", "Single");
        gameLibrary.addGame("Strategy", "Omerta: City of Gangsters", "Single");
        gameLibrary.addGame("Strategy", "Hearts of Iron IV", "Single");
        gameLibrary.addGame("Strategy", "Hearts of Iron IV", "Multi");
        gameLibrary.addGame("Strategy", "Beholder", "Single");
        gameLibrary.addGame("Strategy", "Партизаны 1941", "Single");


        // Приключенческие игры
        gameLibrary.addGame("Adventure", "The Legend of Zelda: A Link to the Past", "Single");
        gameLibrary.addGame("Adventure", "Tomb Raider", "Single");
        gameLibrary.addGame("Adventure", "Tomb Raider II", "Single");
        gameLibrary.addGame("Adventure", "Shenmue", "Single");
        gameLibrary.addGame("Adventure", "Indiana Jones and the Infernal Machine", "Single");
        gameLibrary.addGame("Adventure", "Shenmue II", "Single");
        gameLibrary.addGame("Adventure", "Indiana Jones & The Emperor's Tomb", "Single");
        gameLibrary.addGame("Adventure", "Tomb Raider: Legend", "Single");
        gameLibrary.addGame("Adventure", "Tomb Raider: Anniversary", "Single");
        gameLibrary.addGame("Adventure", "Batman: The Telltale Series", "Single");
        gameLibrary.addGame("Adventure", "Outer Wilds", "Single");

        // Симуляторы
        gameLibrary.addGame("Simulator", "Дальнобойщики 2", "Single");
        gameLibrary.addGame("Simulator", "Дальнобойщики 2", "Multi");
        gameLibrary.addGame("Simulator", "The Sims 3", "Single");
        gameLibrary.addGame("Simulator", "Plague Inc.", "Single");
        gameLibrary.addGame("Simulator", "Euro Truck Simulator 2", "Single");
        gameLibrary.addGame("Simulator", "Euro Truck Simulator 2", "Multi");
        gameLibrary.addGame("Simulator", "The Sims 4", "Single");
        gameLibrary.addGame("Simulator", "BeamNG.drive", "Single");
        gameLibrary.addGame("Simulator", "BeamNG.drive", "Multi");
        gameLibrary.addGame("Simulator", "Cities: Skylines", "Single");
        gameLibrary.addGame("Simulator", "Stardew Valley", "Single");
        gameLibrary.addGame("Simulator", "Stardew Valley", "Multi");
        gameLibrary.addGame("Simulator", "Star Wars: Squadrons", "Single");
        gameLibrary.addGame("Simulator", "Star Wars: Squadrons", "Multi");

        // Гонки
        gameLibrary.addGame("Racing", "The Need for Speed", "Single");
        gameLibrary.addGame("Racing", "The Need for Speed", "Multi");
        gameLibrary.addGame("Racing", "Road Rash 3: Tour de Force", "Single");
        gameLibrary.addGame("Racing", "Road Rash 3: Tour de Force", "Multi");
        gameLibrary.addGame("Racing", "Twisted Metal", "Single");
        gameLibrary.addGame("Racing", "Twisted Metal", "Multi");
        gameLibrary.addGame("Racing", "Carmageddon", "Single");
        gameLibrary.addGame("Racing", "Carmageddon", "Multi");
        gameLibrary.addGame("Racing", "Дальнобойщики: Путь к победе", "Single");
        gameLibrary.addGame("Racing", "Дальнобойщики: Путь к победе", "Multi");
        gameLibrary.addGame("Racing", "Gran Turismo", "Single");
        gameLibrary.addGame("Racing", "Gran Turismo", "Multi");
        gameLibrary.addGame("Racing", "Crazy Taxi", "Single");
        gameLibrary.addGame("Racing", "Midnight Club: Street Racing", "Single");
        gameLibrary.addGame("Racing", "Midnight Club: Street Racing", "Multi");
        gameLibrary.addGame("Racing", "Need for Speed: Porsche", "Single");
        gameLibrary.addGame("Racing", "Need for Speed: Porsche", "Multi");
        gameLibrary.addGame("Racing", "FlatOut", "Single");
        gameLibrary.addGame("Racing", "FlatOut", "Multi");
        gameLibrary.addGame("Racing", "FlatOut", "Single");
        gameLibrary.addGame("Racing", "FlatOut", "Multi");
        gameLibrary.addGame("Racing", "Blur", "Single");
        gameLibrary.addGame("Racing", "Blur", "Multi");
        gameLibrary.addGame("Racing", "Carmageddon: Reincarnation", "Single");
        gameLibrary.addGame("Racing", "Carmageddon: Reincarnation", "Multi");
        // Спортивные игры
        gameLibrary.addGame("Sport", "WWF WrestleMania", "Single");
        gameLibrary.addGame("Sport", "WWF WrestleMania", "Multi");
        gameLibrary.addGame("Sport", "FIFA International Soccer", "Single");
        gameLibrary.addGame("Sport", "FIFA International Soccer", "Multi");
        gameLibrary.addGame("Sport", "FIFA Soccer 95", "Single");
        gameLibrary.addGame("Sport", "FIFA Soccer 95", "Multi");
        gameLibrary.addGame("Sports", "FIFA 97", "Single");
        gameLibrary.addGame("Sports", "FIFA 97", "Multi");
        gameLibrary.addGame("Sport", "Tony Hawk’s Pro Skater", "Single");
        gameLibrary.addGame("Sport", "Tony Hawk’s Pro Skater", "Multi");
        gameLibrary.addGame("Sport", "FIFA Football 2002", "Single");
        gameLibrary.addGame("Sport", "FIFA Football 2002", "Multi");
        gameLibrary.addGame("Sport", "Skate", "Single");
        gameLibrary.addGame("Sport", "WWE SmackDown vs. Raw 2010", "Single");
        gameLibrary.addGame("Sport", "WWE SmackDown vs. Raw 2010", "Multi");
        // Квестовые игры
        gameLibrary.addGame("Quest", "King’s Quest V: Absence Makes the Heart Go Yonder!", "Single");
        gameLibrary.addGame("Quest", "King’s Quest VI: Heir Today, Gone Tomorrow", "Single");
        gameLibrary.addGame("Quest", "Indiana Jones and the Fate of Atlantis", "Single");
        gameLibrary.addGame("Quest", "Sam & Max Hit the Road", "Single");
        gameLibrary.addGame("Quest", "The Neverhood", "Single");
        gameLibrary.addGame("Quest", "Syberia", "Single");
        gameLibrary.addGame("Quest", "Valiant Hearts: The Great War", "Single");
        // Платформеры
        gameLibrary.addGame("Platformer", "Sonic Adventure 2", "Single");
        gameLibrary.addGame("Platformer", "Sonic Adventure 2", "Multi");
        gameLibrary.addGame("Platformer", "Crash Bandicoot N. Sane Trilogy", "Single");
        gameLibrary.addGame("Platformer", "Sonic Mania", "Single");
        gameLibrary.addGame("Platformer", "Sonic Mania", "Multi");
        gameLibrary.addGame("Platformer", "Super Mario Bros. 3", "Single");
        gameLibrary.addGame("Platformer", "Super Mario Bros. 3", "Multi");
        gameLibrary.addGame("Platformer", "Commander Keen in Invasion of the Vorticons", "Single");
        gameLibrary.addGame("Platformer", "Mega Man 3", "Single");
        gameLibrary.addGame("Platformer", "Duke Nukem", "Single");
        gameLibrary.addGame("Platformer", "Sonic the Hedgehog", "Single");
        gameLibrary.addGame("Platformer", "Samurai Pizza Cats", "Single");
        gameLibrary.addGame("Platformer", "Felix the Cat", "Single");
        gameLibrary.addGame("Platformer", "Sonic the Hedgehog 2", "Single");
        gameLibrary.addGame("Platformer", "Sonic the Hedgehog 2", "Multi");
        gameLibrary.addGame("Platformer", "Duke Nukem II", "Single");
        gameLibrary.addGame("Platformer", "Sonic the Hedgehog CD", "Single");
        gameLibrary.addGame("Platformer", "Earthworm Jim", "Single");
        gameLibrary.addGame("Platformer", "Sonic the Hedgehog 3", "Single");
        gameLibrary.addGame("Platformer", "Sonic the Hedgehog 3", "Multi");
        gameLibrary.addGame("Platformer", "Earthworm Jim 2", "Single");
        gameLibrary.addGame("Platformer", "Rayman", "Single");
        gameLibrary.addGame("Platformer", "Crash Bandicoot", "Single");
        gameLibrary.addGame("Platformer", "Crash Bandicoot 2: Cortex Strikes Back", "Single");
        gameLibrary.addGame("Platformer", "Crash Bandicoot: Warped", "Single");
        gameLibrary.addGame("Platformer", "Jet Set Radio", "Single");
        // Beat 'em up
        gameLibrary.addGame("Beat 'em up", "Streets of Rage", "Single");
        gameLibrary.addGame("Beat 'em up", "Streets of Rage", "Multi");
        gameLibrary.addGame("Beat 'em up", "Alien vs Predator", "Single");
        gameLibrary.addGame("Beat 'em up", "Yakuza", "Single");
        // Хорроры
        gameLibrary.addGame("Horror", "Alone in the Dark", "Single");
        gameLibrary.addGame("Horror", "Alone in the Dark 2", "Single");
        gameLibrary.addGame("Horror", "Resident Evil", "Single");
        gameLibrary.addGame("Horror", "Dino Crisis", "Single");
        gameLibrary.addGame("Horror", "Silent Hill 3", "Single");
        gameLibrary.addGame("Horror", "Resident Evil 4", "Single");
        gameLibrary.addGame("Horror", "Dead Space", "Single");
        gameLibrary.addGame("Horror", "Deadly Premonition", "Single");
        gameLibrary.addGame("Horror", "Cry of Fear", "Single");
        gameLibrary.addGame("Horror", "The Evil Within", "Single");
        gameLibrary.addGame("Horror", "Doki Doki Literature Club!", "Single");
        gameLibrary.addGame("Horror", "The Forest", "Single");
        gameLibrary.addGame("Horror", "The Forest", "Multi");
        gameLibrary.addGame("Horror", "Resident Evil 2 Remake", "Single");
        // Файтинги
        gameLibrary.addGame("Fighting", "Street Fighter II", "Single");
        gameLibrary.addGame("Fighting", "Street Fighter II", "Multi");
        gameLibrary.addGame("Fighting", "Mortal Kombat", "Multi");
        gameLibrary.addGame("Fighting", "JoJo’s Bizarre Adventure", "Single");
        gameLibrary.addGame("Fighting", "Mortal Kombat II", "Multi");
        gameLibrary.addGame("Fighting", "Mortal Kombat 3", "Single");
        gameLibrary.addGame("Fighting", "Mortal Kombat 3", "Multi");
        gameLibrary.addGame("Fighting", "Tekken", "Single");
        gameLibrary.addGame("Fighting", "Tekken", "Multi");
        gameLibrary.addGame("Fighting", "Mortal Kombat Trilogy", "Single");
        gameLibrary.addGame("Fighting", "Mortal Kombat Trilogy", "Multi");
        gameLibrary.addGame("Fighting", "JoJo’s Bizarre Adventure: Eyes of Heaven", "Single");
        gameLibrary.addGame("Fighting", "JoJo’s Bizarre Adventure: Eyes of Heaven", "Multi");
        // MMO
        gameLibrary.addGame("MMO", "Lineage II", "Multi");
        gameLibrary.addGame("MMO", "The Elder Scrolls Online", "Multi");


        // Получаем параметры от пользователя
        System.out.println("Введите жанр игры:");
        String genre = scanner.nextLine();

        System.out.println("Введите тип игры(количество игроков):");
        String playType = scanner.nextLine();

        // Выводим игры по заданным параметрам
        gameLibrary.printGamesByParameters(genre, playType);
    }
}

